### PR TITLE
Fix an issue that somewhat doesn't exist

### PR DESCRIPTION
**Pull request by viral32111**
Okay yes I know that file extensions on Linux don't matter, *but* it does help to identify the type of file without using the file command or opening up the file contents. One could argue the .sh extension means shell script, which is technically true, however it's more likely that people would assume `.sh` means it runs in the `/bin/sh` shell, but the top of each file clearly specifies the executing binary is infact `/bin/bash`, therefore the `.bash` extension is mopre appropriate.

Also the files weren't marked as executable so anyone cloning the repo wouldn't be able to use ./ and whatever to execute them.

### CODE REVIEW

**Comment by viral32111** [comment]
i cant help but notice you labelled it but didnt merge it

sorry are my changes not cursed enough or something

**Comment by viral32111** [comment]
https://github.com/weebi/bashscripts/pull/1/commits/7fa60c130e5c0ef16ac207cc6acdeefdaeb7c8c9, github will hate you otherwise

**Comment by weebi** [comment]
Ah, good catch on the file extensions. That seems much better. 

> Also the files weren't marked as executable

Something seems to be broken since they are marked as executable on my end, I'll have to look further into it.

> Standards man

_Smh._

**Comment by viral32111** [comment]
woo, poggers!

> Something seems to be broken since they are marked as executable on my end, I'll have to look further into it.

recompile git from source ez fix

**Review by weebi — COMMENTED** [review]
Smh.

**Review by weebi — COMMENTED** [review]
Forgot one, _SMH_

**Pull request merged**
